// ── Best in Slot data for Patch 12.0.5 · Lingering Shadows · Season 1 ──────
// Structure: BIS_DATA[classKey][specKey].items = [{slot, item, source, location}]
// Classes without full data show a "coming soon" message in the UI.

const WOW_CLASSES = [
  { key: 'deathknight',  label: 'Death Knight',  color: '#C41E3A', icon: '💀', armor: 'Plate',
    specs: [
      { key: 'blood',   label: 'Blood',   role: 'tank' },
      { key: 'frost',   label: 'Frost',   role: 'dps' },
      { key: 'unholy',  label: 'Unholy',  role: 'dps' },
    ]
  },
  { key: 'demonhunter',  label: 'Demon Hunter',  color: '#A330C9', icon: '👁', armor: 'Leather',
    specs: [
      { key: 'havoc',     label: 'Havoc',     role: 'dps' },
      { key: 'vengeance', label: 'Vengeance', role: 'tank' },
      { key: 'devourer',  label: 'Devourer',  role: 'dps', tag: 'new' },
    ]
  },
  { key: 'druid',        label: 'Druid',         color: '#FF7C0A', icon: '🌿', armor: 'Leather',
    specs: [
      { key: 'balance',     label: 'Balance',     role: 'dps' },
      { key: 'feral',       label: 'Feral',       role: 'dps' },
      { key: 'guardian',    label: 'Guardian',    role: 'tank' },
      { key: 'restoration', label: 'Restoration', role: 'heal' },
    ]
  },
  { key: 'evoker',       label: 'Evoker',         color: '#33937F', icon: '🐉', armor: 'Mail',
    specs: [
      { key: 'augmentation', label: 'Augmentation', role: 'dps' },
      { key: 'devastation',  label: 'Devastation',  role: 'dps' },
      { key: 'preservation', label: 'Preservation', role: 'heal' },
    ]
  },
  { key: 'hunter',       label: 'Hunter',         color: '#AAD372', icon: '🏹', armor: 'Mail',
    specs: [
      { key: 'beastmastery',    label: 'Beast Mastery',    role: 'dps' },
      { key: 'marksmanship',    label: 'Marksmanship',     role: 'dps' },
      { key: 'survival',        label: 'Survival',         role: 'dps' },
    ]
  },
  { key: 'mage',         label: 'Mage',           color: '#3FC7EB', icon: '❄️', armor: 'Cloth',
    specs: [
      { key: 'arcane', label: 'Arcane', role: 'dps' },
      { key: 'fire',   label: 'Fire',   role: 'dps' },
      { key: 'frost',  label: 'Frost',  role: 'dps' },
    ]
  },
  { key: 'monk',         label: 'Monk',           color: '#00FF98', icon: '☯️', armor: 'Leather',
    specs: [
      { key: 'brewmaster',  label: 'Brewmaster',  role: 'tank' },
      { key: 'mistweaver',  label: 'Mistweaver',  role: 'heal' },
      { key: 'windwalker',  label: 'Windwalker',  role: 'dps' },
    ]
  },
  { key: 'paladin',      label: 'Paladin',        color: '#F48CBA', icon: '⚔️', armor: 'Plate',
    specs: [
      { key: 'holy',        label: 'Holy',        role: 'heal' },
      { key: 'protection',  label: 'Protection',  role: 'tank' },
      { key: 'retribution', label: 'Retribution', role: 'dps' },
    ]
  },
  { key: 'priest',       label: 'Priest',         color: '#FFFFFF', icon: '✨', armor: 'Cloth',
    specs: [
      { key: 'discipline', label: 'Discipline', role: 'heal' },
      { key: 'holy',       label: 'Holy',       role: 'heal' },
      { key: 'shadow',     label: 'Shadow',     role: 'dps' },
    ]
  },
  { key: 'rogue',        label: 'Rogue',          color: '#FFF468', icon: '🗡️', armor: 'Leather',
    specs: [
      { key: 'assassination', label: 'Assassination', role: 'dps' },
      { key: 'outlaw',        label: 'Outlaw',        role: 'dps' },
      { key: 'subtlety',      label: 'Subtlety',      role: 'dps' },
    ]
  },
  { key: 'shaman',       label: 'Shaman',         color: '#0070DD', icon: '⚡', armor: 'Mail',
    specs: [
      { key: 'elemental',   label: 'Elemental',   role: 'dps' },
      { key: 'enhancement', label: 'Enhancement', role: 'dps' },
      { key: 'restoration', label: 'Restoration', role: 'heal' },
    ]
  },
  { key: 'warlock',      label: 'Warlock',        color: '#8788EE', icon: '🔥', armor: 'Cloth',
    specs: [
      { key: 'affliction',  label: 'Affliction',  role: 'dps' },
      { key: 'demonology',  label: 'Demonology',  role: 'dps' },
      { key: 'destruction', label: 'Destruction', role: 'dps' },
    ]
  },
  { key: 'warrior',      label: 'Warrior',        color: '#C69B3A', icon: '🛡️', armor: 'Plate',
    specs: [
      { key: 'arms',       label: 'Arms',       role: 'dps' },
      { key: 'fury',       label: 'Fury',       role: 'dps' },
      { key: 'protection', label: 'Protection', role: 'tank' },
    ]
  },
];

// ── BiS Gear Lists ────────────────────────────────────────────────────────────
// Slot order follows standard WoW character sheet (top-to-bottom left column,
// then right column, then weapons).
const BIS_DATA = {

  warrior: {
    arms: { items: [
      { slot: 'Head',      item: "Night Ender's Tusks",         source: 'Tier Set',                  location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Ribbon of Coiled Malice',     source: 'Fallen-King Salhadaar',      location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Night Ender's Pauldrons",     source: 'Tier Set',                  location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",    source: 'Crafted',                   location: 'Leatherworking' },
      { slot: 'Chest',     item: "Night Ender's Breastplate",   source: 'Chimaerus',                 location: 'The Dreamrift' },
      { slot: 'Wrists',    item: "Spellbreaker's Bracers",      source: 'Crafted',                   location: 'Blacksmithing' },
      { slot: 'Hands',     item: 'Embergrove Grasps',           source: 'Dungeon Drop',              location: 'Windrunner Spire (M+)' },
      { slot: 'Waist',     item: "Night Ender's Girdle",        source: 'Tier Catalyst',             location: 'Great Vault / Catalyst' },
      { slot: 'Legs',      item: "Night Ender's Chausses",      source: 'Tier Set',                  location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Greaves of the Unformed',     source: 'Chimaerus',                 location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',             source: 'Midnight Falls',            location: 'March on Quel\'Danas' },
      { slot: 'Ring 2',    item: 'Occlusion of Void',           source: 'Dungeon Drop',              location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',         source: 'Chimaerus',                 location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: 'Heart of Ancient Hunger',     source: 'Vorasius',                  location: 'The Voidspire' },
      { slot: 'Main Hand', item: "Alah'endal, the Dawnsong",    source: 'Midnight Falls',            location: 'March on Quel\'Danas' },
    ]},
    fury: { items: [
      { slot: 'Head',      item: "Night Ender's Tusks",             source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',      source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: "Night Ender's Pauldrons",         source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Rigid Scale Greatcloak',          source: 'Dungeon Drop',          location: 'Skyreach (M+)' },
      { slot: 'Chest',     item: "Night Ender's Breastplate",       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Spellbreaker's Bracers",          source: 'Crafted',               location: 'Blacksmithing' },
      { slot: 'Hands',     item: 'Voidclaw Gauntlets',              source: 'Viceroy Nezhar',        location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Waist',     item: "Night Ender's Girdle",            source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Legs',      item: "Night Ender's Chausses",          source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "Night Ender's Greatboots",        source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Ring 1',    item: 'Platinum Star Band',              source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Ring 2',    item: 'Eye of Midnight',                 source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',             source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: 'Heart of Ancient Hunger',         source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Main Hand', item: "Bellamy's Final Judgement",       source: 'Lightblinded Vanguard', location: "March on Quel'Danas" },
      { slot: 'Off Hand',  item: "Blood Knight's Impetus",          source: 'Crafted',               location: 'Blacksmithing' },
    ]},
    protection: { items: [
      { slot: 'Head',      item: "Night Ender's Tusks",             source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',          source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Night Ender's Pauldrons",         source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",        source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: "Night Ender's Breastplate",       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Spellbreaker's Bracers",          source: 'Crafted',               location: 'Blacksmithing' },
      { slot: 'Hands',     item: 'Voidclaw Gauntlets',              source: 'Viceroy Nezhar',        location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Waist',     item: "Night Ender's Girdle",            source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Legs',      item: "Night Ender's Chausses",          source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "Night Ender's Greatboots",        source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                 source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Occlusion of Void',               source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: "Algeth'ar Puzzle Box",            source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',             source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Main Hand', item: "Turalyon's False Echo",           source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Shield',    item: 'Ward of the Spellbreaker',        source: 'Seranel Sunlash',       location: "Magister's Terrace (M+)" },
    ]},
  },

  paladin: {
    holy:       { items: [
      { slot: 'Head',      item: "Luminant Verdict's Unwavering Gaze",  source: 'Lightblinded Vanguard', location: "March on Quel'Danas" },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',          source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: "Luminant Verdict's Providence Watch",  source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Back',      item: 'Rigid Scale Greatcloak',               source: 'Dungeon Drop',          location: 'Skyreach (M+)' },
      { slot: 'Chest',     item: "Luminant Verdict's Divine Warplate",   source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Wrists',    item: "Trollhunter's Bands",                  source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
      { slot: 'Hands',     item: "Luminant Verdict's Gauntlets",         source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Waist',     item: "Ezzorak's Gloombind",                  source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Legs',      item: 'Extinction Guards',                    source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Feet',      item: 'Parasite Stompers',                    source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                      source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: "Sin'dorei Band of Hope",               source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: "Locus-Walker's Ribbon",                source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',                  source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Main Hand', item: 'Spellboon Saber',                      source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Shield',    item: "Viryx's Indomitable Bulwark",          source: 'High Sage Viryx',       location: 'Skyreach (M+)' },
    ]},
    protection: { items: [
      { slot: 'Head',      item: "Luminant Verdict's Unwavering Gaze",  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',               source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Luminant Verdict's Providence Watch",  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Shroud of the Soulhunter',             source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
      { slot: 'Chest',     item: "Luminant Verdict's Divine Warplate",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Spellbreaker's Bracers",               source: 'Crafted',               location: 'Blacksmithing' },
      { slot: 'Hands',     item: 'Voidclaw Gauntlets',                   source: 'Viceroy Nezhar',        location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Waist',     item: 'Shadowsplit Girdle',                   source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Legs',      item: "Luminant Verdict's Greaves",           source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Aetherlume Stompers',                  source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Ring 1',    item: 'Occlusion of Void',                    source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Ring 2',    item: 'Omission of Light',                    source: 'Corewarden Nysarra',    location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Umbral Plume',                         source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Trinket 2', item: "Algeth'ar Puzzle Box",                 source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Main Hand', item: "Turalyon's False Echo",                source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Shield',    item: 'Bulwark of Noble Resolve',             source: 'Dungeon Drop',          location: 'Seat of the Triumvirate (M+)' },
    ]},
    retribution: { items: [
      { slot: 'Head',      item: "Luminant Verdict's Unwavering Gaze",  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',          source: 'Midnight Falls',        location: 'March on Quel\'Danas' },
      { slot: 'Shoulders', item: "Luminant Verdict's Providence Watch", source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",            source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: "Luminant Verdict's Divine Warplate",  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Spellbreaker's Bracers",              source: 'Crafted',               location: 'Blacksmithing' },
      { slot: 'Hands',     item: 'Voidclaw Gauntlets',                  source: 'Dungeon Drop',          location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Waist',     item: 'Hate-Tied Waistchain',                source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Legs',      item: "Luminant Verdict's Greaves",          source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Greaves of the Unformed',             source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                     source: 'Midnight Falls',        location: 'March on Quel\'Danas' },
      { slot: 'Ring 2',    item: "Sin'dorei Band of Hope",              source: "Belo'ren",              location: 'March on Quel\'Danas' },
      { slot: 'Trinket 1', item: 'Umbral Plume',                        source: "Belo'ren",              location: 'March on Quel\'Danas' },
      { slot: 'Trinket 2', item: "Algeth'ar Puzzle Box",                source: 'Dungeon Drop',          location: "Algeth'ar Academy (M+)" },
      { slot: 'Main Hand', item: "Bellamy's Final Judgement",           source: 'Lightblinded Vanguard', location: 'March on Quel\'Danas' },
    ]},
  },

  deathknight: {
    blood:  { items: [
      { slot: 'Head',      item: "Relentless Rider's Crown",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',          source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Relentless Rider's Dreadthorns",  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",        source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: "Relentless Rider's Cuirass",      source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Spellbreaker's Bracers",          source: 'Crafted',               location: 'Blacksmithing' },
      { slot: 'Hands',     item: 'Voidclaw Gauntlets',              source: 'Viceroy Nezhar',        location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Waist',     item: "Ezzorak's Gloombind",             source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Legs',      item: "Relentless Rider's Legguards",    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Greaves of the Unformed',         source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Occlusion of Void',               source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Ring 2',    item: 'Omission of Light',               source: 'Corewarden Nysarra',    location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',             source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Algeth'ar Puzzle Box",            source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Main Hand', item: "Alah'endal, the Dawnsong",        source: "Midnight Falls",        location: "March on Quel'Danas" },
    ]},
    frost:  { items: [
      { slot: 'Head',      item: "Relentless Rider's Crown",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',      source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: 'Shoulderplates of Frozen Blood',  source: 'Forgemaster Garfrost',  location: 'Pit of Saron (M+)' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",        source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: "Relentless Rider's Cuirass",      source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Spellbreaker's Bracers",          source: 'Crafted',               location: 'Blacksmithing' },
      { slot: 'Hands',     item: "Relentless Rider's Bonegrasps",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Hate-Tied Waistchain',            source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Legs',      item: "Relentless Rider's Legguards",    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Greaves of the Unformed',         source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Platinum Star Band',              source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Ring 2',    item: "Sin'dorei Band of Hope",          source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Light Company Guidon',            source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',             source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Main Hand', item: 'Blade of the Final Twilight',     source: 'Dungeon Drop',          location: 'Pit of Saron (M+)' },
      { slot: 'Off Hand',  item: 'Blade of the Final Twilight',     source: 'Dungeon Drop',          location: 'Pit of Saron (M+)' },
    ]},
    unholy: { items: [
      { slot: 'Head',      item: "Relentless Rider's Crown",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',      source: 'Midnight Falls',        location: 'March on Quel\'Danas' },
      { slot: 'Shoulders', item: 'Shoulderplates of Frozen Blood',  source: 'Dungeon Drop',          location: 'Pit of Saron (M+)' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",        source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: "Relentless Rider's Cuirass",      source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Spellbreaker's Bracers",          source: 'Crafted',               location: 'Blacksmithing' },
      { slot: 'Hands',     item: "Relentless Rider's Bonegrasps",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Relentless Rider's Chain",        source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Legs',      item: "Relentless Rider's Legguards",    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Greaves of the Unformed',         source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Platinum Star Band',              source: 'Dungeon Drop',          location: "Algeth'ar Academy (M+)" },
      { slot: 'Ring 2',    item: "Sin'dorei Band of Hope",          source: "Belo'ren",              location: 'March on Quel\'Danas' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',             source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: 'Light Company Guidon',            source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Main Hand', item: "Bellamy's Final Judgement",       source: 'Lightblinded Vanguard', location: 'March on Quel\'Danas' },
    ]},
  },

  demonhunter: {
    havoc:     { items: [
      { slot: 'Head',      item: "Spellsnap Shadowmask",               source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',         source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: "Devouring Reaver's Exhaustplates",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Rigid Scale Greatcloak',             source: 'Dungeon Drop',          location: 'Skyreach (M+)' },
      { slot: 'Chest',     item: "Devouring Reaver's Engine",          source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Silvermoon Agent's Deflectors",      source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Hands',     item: "Devouring Reaver's Essence Grips",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Snapvine Cinch',                     source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Legs',      item: "Devouring Reaver's Pistons",         source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "Silvermoon Agent's Sneakers",        source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: "Sin'dorei Band of Hope",             source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Platinum Star Band',                 source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Algeth'ar Puzzle Box",               source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Main Hand', item: 'Lightless Lament',                   source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Off Hand',  item: 'Soulblight Cleaver',                 source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
    ]},
    vengeance: { items: [
      { slot: 'Head',      item: "Devouring Reaver's Intake",          source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',             source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Devouring Reaver's Exhaustplates",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Potionstained Cloak',                source: 'Crafted',               location: 'Alchemy' },
      { slot: 'Chest',     item: "Vest of the Void's Embrace",         source: 'Dungeon Drop',          location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Wrists',    item: "Silvermoon Agent's Deflectors",      source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Hands',     item: "Devouring Reaver's Essence Grips",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Cinch of the Umbral Lasher',         source: 'Dungeon Drop',          location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Legs',      item: "Devouring Reaver's Pistons",         source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Voidclaimed Shinkickers',            source: 'Dungeon Drop',          location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Ring 1',    item: 'Purloined Wedding Ring',             source: 'Ick and Krick',         location: 'Pit of Saron (M+)' },
      { slot: 'Ring 2',    item: 'Occlusion of Void',                  source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: 'Umbral Plume',                       source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Main Hand', item: 'Dawncrazed Beast Cleaver',           source: "Lu'ashal",              location: 'World Boss' },
      { slot: 'Off Hand',  item: "Spellbreaker's Warglaive",           source: 'Crafted',               location: 'Blacksmithing' },
    ]},
    devourer:  { items: [
      { slot: 'Head',      item: "Devouring Reaver's Intake",          source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',             source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Devouring Reaver's Exhaustplates",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Draconic Nullcape',                  source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Chest',     item: "Devouring Reaver's Engine",          source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: 'Frenzyroot Cuffs',                   source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Hands',     item: "Devouring Reaver's Essence Grips",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Bloodfeather Girdle',                source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Legs',      item: 'Shaggy Wyrmleather Leggings',        source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
      { slot: 'Feet',      item: "Silvermoon Agent's Sneakers",        source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: 'Bond of Light',                      source: 'Lightblinded Vanguard', location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Eye of Midnight',                    source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Vaelgor's Final Stare",              source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Main Hand', item: 'Lightless Lament',                   source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Off Hand',  item: "Spellbreaker's Warglaive",           source: 'Crafted',               location: 'Blacksmithing' },
    ]},
  },

  druid: {
    balance:     { items: [
      { slot: 'Head',      item: 'Branches of the Luminous Bloom',    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',        source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: 'Seedpods of the Luminous Bloom',    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",          source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: 'Trunk of the Luminous Bloom',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: 'Voidskinned Bracers',               source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Hands',     item: 'Gloves of Viscous Goo',             source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
      { slot: 'Waist',     item: 'Snapvine Cinch',                    source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Legs',      item: 'Phloemwraps of the Luminous Bloom', source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "Canopy Walker's Footwraps",         source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: 'Occlusion of Void',                 source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Ring 2',    item: 'Omission of Light',                 source: 'Corewarden Nysarra',    location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: "Vaelgor's Final Stare",             source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',               source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Main Hand', item: 'Splitshroud Stinger',               source: 'Gemellus',              location: "Magister's Terrace (M+)" },
      { slot: 'Off Hand',  item: "Aln'hara Lantern",                  source: 'Crafted',               location: 'Enchanting' },
    ]},
    feral:       { items: [
      { slot: 'Head',      item: 'Branches of the Luminous Bloom',    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',        source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: "Fallen Grunt's Mantle",             source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Back',      item: "Defiant Defender's Drape",          source: 'Dungeon Drop',          location: "Magister's Terrace (M+)" },
      { slot: 'Chest',     item: 'Trunk of the Luminous Bloom',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Silvermoon Agent's Deflectors",     source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Hands',     item: 'Arbortenders of the Luminous Bloom',source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Scornscarred Shul'ka's Belt",       source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Legs',      item: 'Phloemwraps of the Luminous Bloom', source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "Canopy Walker's Footwraps",         source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                   source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: "Loa Worshiper's Band",              source: 'Crafted',               location: 'Jewelcrafting' },
      { slot: 'Trinket 1', item: "Algeth'ar Puzzle Box",              source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',               source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Main Hand', item: "Roostwarden's Bough",               source: 'Emberdawn',             location: 'Windrunner Spire (M+)' },
    ]},
    guardian:    { items: [
      { slot: 'Head',      item: 'Mask of Darkest Intent',            source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Neck',      item: 'Pendant of Aching Grief',           source: 'Restless Heart',        location: 'Windrunner Spire (M+)' },
      { slot: 'Shoulders', item: 'Seedpods of the Luminous Bloom',    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Potionstained Cloak',               source: 'Crafted',               location: 'Alchemy' },
      { slot: 'Chest',     item: 'Trunk of the Luminous Bloom',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Silvermoon Agent's Deflectors",     source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Hands',     item: 'Arbortenders of the Luminous Bloom',source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Silvermoon Agent's Utility Belt",   source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Legs',      item: 'Phloemwraps of the Luminous Bloom', source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Eclipse Espadrilles',               source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Ring 1',    item: 'Omission of Light',                 source: 'Corewarden Nysarra',    location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Ring 2',    item: 'Occlusion of Void',                 source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: "Algeth'ar Puzzle Box",              source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Trinket 2', item: 'Umbral Plume',                      source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Main Hand', item: "Traitor's Talon",                   source: "Muro'jin & Nekraxx",    location: 'Maisara Caverns (M+)' },
    ]},
    restoration: { items: [
      { slot: 'Head',      item: 'Oblivion Guise',                    source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Neck',      item: 'Ribbon of Coiled Malice',           source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Shoulders', item: 'Seedpods of the Luminous Bloom',    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Guardian of the Primal Core',       source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Chest',     item: 'Trunk of the Luminous Bloom',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: 'Cuffs of the Primal Core',          source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Hands',     item: 'Arbortenders of the Luminous Bloom',source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Waistcord of the Judged',           source: 'Lightblinded Vanguard', location: "March on Quel'Danas" },
      { slot: 'Legs',      item: 'Phloemwraps of the Luminous Bloom', source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Sabatons of Obscurement',           source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Ring 1',    item: "Sin'dorei Band of Hope",            source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Platinum Star Band',                source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',               source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Locus-Walker's Ribbon",             source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Main Hand', item: 'Weight of Command',                 source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Off Hand',  item: "Aln'hara Lantern",                  source: 'Crafted',               location: 'Enchanting' },
    ]},
  },

  evoker: {
    augmentation: { items: [
      { slot: 'Head',      item: 'Horns of the Spurned Valkyr',      source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Neck',      item: 'Ribbon of Coiled Malice',          source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Shoulders', item: 'Beacons of the Black Talon',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",         source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: 'Frenzyward of the Black Talon',    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Farstrider's Plated Bracers",      source: 'Crafted',               location: 'Blacksmithing' },
      { slot: 'Hands',     item: "Enforcer's Grips of the Black Talon", source: 'Tier Set',           location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Scabrous Zombie Belt',             source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Legs',      item: 'Greaves of the Black Talon',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Spelltreads of the Black Talon',   source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                  source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Purloined Wedding Ring',           source: 'Ick and Krick',         location: 'Pit of Saron (M+)' },
      { slot: 'Trinket 1', item: 'Shadow of the Empyrean Requiem',   source: "L'ura",                 location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Trinket 2', item: "Soulcatcher's Charm",              source: 'Vordaza',               location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Main Hand', item: 'Ceremonial Hexblade',              source: 'Vordaza',               location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Off Hand',  item: 'Grimoire of the Eternal Light',    source: 'Vorasius',              location: 'The Voidspire' },
    ]},
    devastation:  { items: [
      { slot: 'Head',      item: 'Hornhelm of the Black Talon',      source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',       source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: 'Beacons of the Black Talon',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",         source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: 'Frenzyward of the Black Talon',    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Farstrider's Plated Bracers",      source: 'Crafted',               location: 'Blacksmithing' },
      { slot: 'Hands',     item: "Untethered Berserker's Grips",     source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Waist',     item: 'Scabrous Zombie Leather Belt',     source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Legs',      item: 'Greaves of the Black Talon',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Spelltreads of the Black Talon',   source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Ring 1',    item: "Sin'dorei Band of Hope",           source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Eye of Midnight',                  source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',              source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Vaelgor's Final Stare",            source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Main Hand', item: "Belo'melorn, the Shattered Talon", source: 'Void Ember',            location: "March on Quel'Danas" },
      { slot: 'Off Hand',  item: 'Grimoire of the Eternal Light',    source: 'Vorasius',              location: 'The Voidspire' },
    ]},
    preservation: { items: [
      { slot: 'Head',      item: 'Oblivion Guise',                   source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',       source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: 'Beacons of the Black Talon',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Fluxweave Cloak',                  source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Chest',     item: 'Frenzyward of the Black Talon',    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: 'Amberfrond Bracers',               source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Hands',     item: "Enforcer's Grips of the Black Talon", source: 'Tier Set',           location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Azure Belt of Competition',        source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Legs',      item: 'Greaves of the Black Talon',       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Whipcoil Sabatons',                source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Ring 1',    item: 'Bond of Light',                    source: 'Lightblinded Vanguard', location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Eye of Midnight',                  source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',              source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Locus-Walker's Ribbon",            source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Main Hand', item: 'Umbral Spire of Zuraal',           source: 'Zuraal the Ascended',   location: 'Seat of the Triumvirate (M+)' },
    ]},
  },

  hunter: {
    beastmastery: { items: [
      { slot: 'Head',      item: "Primal Sentry's Maw",                  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',           source: 'Midnight Falls',        location: 'March on Quel\'Danas' },
      { slot: 'Shoulders', item: 'Pauldrons of the Void Hunter',         source: 'Dungeon Drop',          location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Back',      item: 'Rigid Scale Greatcloak',               source: 'Dungeon Drop',          location: 'Skyreach (M+)' },
      { slot: 'Chest',     item: "Primal Sentry's Scaleplate",           source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: 'Corewarden Cuffs',                     source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Hands',     item: "Primal Sentry's Talonguards",          source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "World Tender's Barkclasp",             source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Legs',      item: "Primal Sentry's Legguards",            source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "World Tender's Rootslippers",          source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                      source: 'Midnight Falls',        location: 'March on Quel\'Danas' },
      { slot: 'Ring 2',    item: 'Bond of Light',                        source: 'Lightblinded Vanguard', location: 'March on Quel\'Danas' },
      { slot: 'Trinket 1', item: "Ranger-Captain's Iridescent Insignia", source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Algeth'ar Puzzle Box",                 source: 'Dungeon Drop',          location: "Algeth'ar Academy (M+)" },
      { slot: 'Ranged',    item: "Deceiver's Rotbow",                    source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
    ]},
    marksmanship: { items: [
      { slot: 'Head',      item: "Primal Sentry's Maw",               source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',        source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: 'Pauldrons of the Void Hunter',      source: 'Dungeon Drop',          location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Back',      item: "Imperator's Banner",                source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Chest',     item: "Primal Sentry's Scaleplate",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Fallen King's Cuffs",               source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Hands',     item: "Primal Sentry's Talonguards",       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "World Tender's Barkclasp",          source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Legs',      item: "Primal Sentry's Legguards",         source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "World Tender's Rootslippers",       source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: "Sin'dorei Band of Hope",            source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Signet of the Starved Beast',       source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Trinket 1', item: "Algeth'ar Puzzle Box",              source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Trinket 2', item: 'Umbral Plume',                      source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Ranged',    item: "Ranger-Captain's Lethal Recurve",   source: 'Alleria Windrunner',    location: 'The Voidspire' },
    ]},
    survival:     { items: [
      { slot: 'Head',      item: "Primal Sentry's Maw",               source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',        source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: "Nullwalker's Dread Epaulettes",     source: 'Dungeon Drop',          location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",          source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: "Primal Sentry's Scaleplate",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Primal Sentry's Wound Stanchers",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Hands',     item: "Primal Sentry's Talonguards",       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Scornbane Waistguard',              source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
      { slot: 'Legs',      item: "Primal Sentry's Legguards",         source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Whipcoil Sabatons',                 source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Ring 1',    item: 'Omission of Light',                 source: 'Corewarden Nysarra',    location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Ring 2',    item: 'Eye of Midnight',                   source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: "Algeth'ar Puzzle Box",              source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',               source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Main Hand', item: "Belo'ren's Swift Talon",            source: 'Void Ember',            location: "March on Quel'Danas" },
      { slot: 'Off Hand',  item: "Farstrider's Mercy",                source: 'Crafted',               location: 'Blacksmithing' },
    ]},
  },

  mage: {
    arcane: { items: [
      { slot: 'Head',      item: "Voidbreaker's Veil",               source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',       source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: "Voidbreaker's Leyline Nexi",       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Arcanoweave Cloak',                source: 'Crafted',               location: 'Tailoring' },
      { slot: 'Chest',     item: "Voidbreaker's Robe",               source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: 'Arcanoweave Bracers',              source: 'Crafted',               location: 'Tailoring' },
      { slot: 'Hands',     item: "Voidbreaker's Gloves",             source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Whisper-Inscribed Sash',           source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Legs',      item: "Commander's Faded Breeches",       source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Feet',      item: 'Dream-Scorched Striders',          source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: "Sin'dorei Band of Hope",           source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Eye of Midnight',                  source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',              source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Vaelgor's Final Stare",            source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Main Hand', item: "Skybreaker's Blade",               source: 'Ranjit',                location: 'Skyreach (M+)' },
      { slot: 'Off Hand',  item: 'Sigil of the Restless Heart',      source: 'Restless Heart',        location: 'Windrunner Spire (M+)' },
    ]},
    fire:   { items: [
      { slot: 'Head',      item: "Voidbreaker's Veil",               source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',       source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: 'Mantle of Dark Devotion',          source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Back',      item: 'Rigid Scale Greatcloak',           source: 'Dungeon Drop',          location: 'Skyreach (M+)' },
      { slot: 'Chest',     item: "Voidbreaker's Robe",               source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Martyr's Bindings",                source: 'Crafted',               location: 'Tailoring' },
      { slot: 'Hands',     item: "Voidbreaker's Gloves",             source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Voidbreaker's Sage Cord",          source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Legs',      item: "Voidbreaker's Britches",           source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Dream-Scorched Striders',          source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                  source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: "Sin'dorei Band of Hope",           source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',              source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Vaelgor's Final Stare",            source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Main Hand', item: "Skybreaker's Blade",               source: 'Ranjit',                location: 'Skyreach (M+)' },
      { slot: 'Off Hand',  item: "Aln'hara Lantern",                 source: 'Crafted',               location: 'Enchanting' },
    ]},
    frost:  { items: [
      { slot: 'Head',      item: "Voidbreaker's Veil",            source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',    source: 'Midnight Falls',        location: 'March on Quel\'Danas' },
      { slot: 'Shoulders', item: 'Mantle of Dark Devotion',       source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Back',      item: 'Rigid Scale Greatcloak',        source: 'Dungeon Drop',          location: 'Skyreach (M+)' },
      { slot: 'Chest',     item: "Voidbreaker's Robe",            source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Martyr's Bindings",             source: 'Crafted',               location: 'Tailoring' },
      { slot: 'Hands',     item: "Voidbreaker's Gloves",          source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Voidbreaker's Sage Cord",       source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Legs',      item: "Voidbreaker's Britches",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Dream-Scorched Striders',       source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',               source: 'Midnight Falls',        location: 'March on Quel\'Danas' },
      { slot: 'Ring 2',    item: "Sin'dorei Band of Hope",        source: "Belo'ren",              location: 'March on Quel\'Danas' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',           source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Vaelgor's Final Stare",         source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Main Hand', item: "Skybreaker's Blade",            source: 'Dungeon Drop',          location: 'Skyreach (M+)' },
      { slot: 'Off Hand',  item: "Aln'hara Lantern",              source: 'Crafted',               location: 'Enchanting' },
    ]},
  },

  monk: {
    brewmaster:  { items: [
      { slot: 'Head',      item: "Fearsome Visage of Ra-den's Chosen", source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: "Masterwork Sin'dorei Amulet",        source: 'Crafted',               location: 'Jewelcrafting' },
      { slot: 'Shoulders', item: "Aurastones of Ra-den's Chosen",      source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Imperator's Banner",                 source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Chest',     item: "Battle Garb of Ra-den's Chosen",     source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Strikeguards of Ra-den's Chosen",    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Hands',     item: "Thunderfists of Ra-den's Chosen",    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Snapvine Cinch',                     source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Legs',      item: 'Shifting Stalker Hide Pants',        source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
      { slot: 'Feet',      item: 'Footpads of Seeping Dread',          source: 'Dungeon Drop',          location: 'Maisara Caverns (M+)' },
      { slot: 'Ring 1',    item: 'Signet of the Starved Beast',        source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Ring 2',    item: "Loa Worshiper's Band",               source: 'Crafted',               location: 'Jewelcrafting' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: 'Radiant Plume',                      source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Main Hand', item: 'Inescapable Reach',                  source: 'Vorasius',              location: 'The Voidspire' },
    ]},
    mistweaver:  { items: [
      { slot: 'Head',      item: "Fearsome Visage of Ra-den's Chosen", source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Barbed Ymirheim Choker',             source: 'Forgemaster Garfrost',  location: 'Pit of Saron (M+)' },
      { slot: 'Shoulders', item: 'Blooming Barklight Spaulders',       source: 'War Chaplain Senn',     location: 'The Voidspire' },
      { slot: 'Back',      item: "Defiant Defender's Drape",           source: 'Dungeon Drop',          location: "Magister's Terrace (M+)" },
      { slot: 'Chest',     item: "Battle Garb of Ra-den's Chosen",     source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: 'Void-Skinned Bracers',               source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Hands',     item: "Thunderfists of Ra-den's Chosen",    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Scornscarred Shul'ka's Belt",        source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Legs',      item: "Swiftsweepers of Ra-den's Chosen",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "Storm Crashers of Ra-den's Chosen",  source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                    source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Purloined Wedding Ring',             source: 'Ick and Krick',         location: 'Pit of Saron (M+)' },
      { slot: 'Trinket 1', item: 'Litany of Lightblind Wrath',         source: 'Lightblinded Vanguard', location: "March on Quel'Danas" },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Main Hand', item: 'Arcanic of the High Sage',           source: 'High Sage Viryx',       location: 'Skyreach (M+)' },
      { slot: 'Off Hand',  item: 'Grimoire of the Eternal Light',      source: 'Vorasius',              location: 'The Voidspire' },
    ]},
    windwalker:  { items: [
      { slot: 'Head',      item: "Fearsome Visage of Ra-den's Chosen", source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',         source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: "Aurastones of Ra-den's Chosen",      source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Windwrap of Ra-den's Chosen",        source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Chest',     item: "Battle Garb of Ra-den's Chosen",     source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Silvermoon Agent's Deflectors",      source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Hands',     item: "Vaelgor's Fearsome Grasp",           source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Waist',     item: 'Snapvine Cinch',                     source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Legs',      item: "Swiftsweepers of Ra-den's Chosen",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "Canopy Walker's Footwraps",          source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: "Loa Worshiper's Band",               source: 'Crafted',               location: 'Jewelcrafting' },
      { slot: 'Ring 2',    item: 'Eye of Midnight',                    source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Algeth'ar Puzzle Box",               source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Main Hand', item: 'Inescapable Reach',                  source: 'Vorasius',              location: 'The Voidspire' },
    ]},
  },

  priest: {
    discipline: { items: [
      { slot: 'Head',      item: "Blind Oath's Winged Crest",           source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',              source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Blind Oath's Seraphguards",           source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Draconic Nullcape',                   source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Chest',     item: 'Robes of Endless Oblivion',           source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Wrists',    item: 'Voracious Wristwraps',                source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Hands',     item: "Blind Oath's Touch",                  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Arcanoweave Cord',                    source: 'Crafted',               location: 'Tailoring' },
      { slot: 'Legs',      item: "Blind Oath's Leggings",               source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Lightbinder Treads',                  source: 'Dungeon Drop',          location: 'Skyreach (M+)' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                     source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Omission of Light',                   source: 'Corewarden Nysarra',    location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                 source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Vaelgor's Final Stare",               source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Main Hand', item: "Belo'melorn, the Shattered Talon",    source: 'Void Ember',            location: "March on Quel'Danas" },
      { slot: 'Off Hand',  item: "Aln'hara Lantern",                    source: 'Crafted',               location: 'Enchanting' },
    ]},
    holy:       { items: [
      { slot: 'Head',      item: "Blind Oath's Winged Crest",           source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',          source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: "Blind Oath's Seraphguards",           source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Imperator's Banner",                  source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Chest',     item: 'Robes of Endless Oblivion',           source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Wrists',    item: "Blind Oath's Wraps",                  source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Hands',     item: "Blind Oath's Touch",                  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Arcanoweave Cord',                    source: 'Crafted',               location: 'Tailoring' },
      { slot: 'Legs',      item: "Blind Oath's Leggings",               source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Dream-Scorched Striders',             source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Signet of the Starved Beast',         source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Ring 2',    item: "Sin'dorei Band of Hope",              source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: "Locus-Walker's Ribbon",               source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Trinket 2', item: 'Litany of Lightblind Wrath',          source: 'Lightblinded Vanguard', location: "March on Quel'Danas" },
      { slot: 'Main Hand', item: 'Weight of Command',                   source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Off Hand',  item: "Aln'hara Lantern",                    source: 'Crafted',               location: 'Enchanting' },
    ]},
    shadow:     { items: [
      { slot: 'Head',      item: "Blind Oath's Winged Crest",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',       source: 'Midnight Falls',        location: 'March on Quel\'Danas' },
      { slot: 'Shoulders', item: "Blind Oath's Seraphguards",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Draconic Nullcape',                source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Chest',     item: "Blind Oath's Raiment",             source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: 'Wraps of Watchful Wrath',          source: 'Dungeon Drop',          location: "Magister's Terrace (M+)" },
      { slot: 'Hands',     item: "Blind Oath's Touch",               source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Whisper-Inscribed Sash',           source: "Belo'ren",              location: 'March on Quel\'Danas' },
      { slot: 'Legs',      item: "Blind Oath's Leggings",            source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Dream-Scorched Striders',          source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                  source: 'Midnight Falls',        location: 'March on Quel\'Danas' },
      { slot: 'Ring 2',    item: 'Bond of Light',                    source: 'Lightblinded Vanguard', location: 'March on Quel\'Danas' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',              source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Vaelgor's Final Stare",            source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Main Hand', item: "Belo'melorn, the Shattered Talon", source: "Belo'ren",              location: 'March on Quel\'Danas' },
      { slot: 'Off Hand',  item: 'Tome of Alnscorned Regret',        source: 'Chimaerus',             location: 'The Dreamrift' },
    ]},
  },

  rogue: {
    assassination: { items: [
      { slot: 'Head',      item: "Masquerade of the Grim Jest",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Ribbon of Coiled Malice',            source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Venom Casks of the Grim Jest",       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Defiant Defender's Drape",           source: 'Dungeon Drop',          location: "Magister's Terrace (M+)" },
      { slot: 'Chest',     item: "Fantastic Finery of the Grim Jest",  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Silvermoon Agent's Deflectors",      source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Hands',     item: "Sleight of Hand of the Grim Jest",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Scornscarred Shul'ka's Belt",        source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Legs',      item: 'Legwraps of Lingering Legacies',     source: 'Dungeon Drop',          location: "Magister's Terrace (M+)" },
      { slot: 'Feet',      item: "Canopy Walker's Footwraps",          source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                    source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: "Sin'dorei Band of Hope",             source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Algeth'ar Puzzle Box",               source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Main Hand', item: 'Hungering Victory',                  source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Off Hand',  item: "Farstrider's Mercy",                 source: 'Crafted',               location: 'Blacksmithing' },
    ]},
    outlaw:        { items: [
      { slot: 'Head',      item: 'Voidlashed Hood',                    source: 'Dungeon Drop',          location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Neck',      item: 'Ribbon of Coiled Malice',            source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Venom Casks of the Grim Jest",       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Potionstained Cloak',                source: 'Crafted',               location: 'Alchemy' },
      { slot: 'Chest',     item: "Fantastic Finery of the Grim Jest",  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Silvermoon Agent's Deflectors",      source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Hands',     item: "Sleight of Hand of the Grim Jest",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Scornscarred Shul'ka's Belt",        source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Legs',      item: "Blade Holsters of the Grim Jest",    source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: "Silvermoon Agent's Sneakers",        source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                    source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Signet of the Starved Beast',        source: 'Vorasius',              location: 'The Voidspire' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: 'Umbral Plume',                       source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Main Hand', item: "Arator's Swift Remembrance",         source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Off Hand',  item: "Krick's Beetle Stabber",             source: 'Ick and Krick',         location: 'Pit of Saron (M+)' },
    ]},
    subtlety:      { items: [
      { slot: 'Head',      item: "Masquerade of the Grim Jest",        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',             source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Shoulders', item: "Venom Casks of the Grim Jest",       source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Rigid Scale Greatcloak',             source: 'Dungeon Drop',          location: 'Skyreach (M+)' },
      { slot: 'Chest',     item: "Fantastic Finery of the Grim Jest",  source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Silvermoon Agent's Deflectors",      source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Hands',     item: "Sleight of Hand of the Grim Jest",   source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Snapvine Cinch',                     source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Legs',      item: 'Power Stance Breeches',              source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Feet',      item: "Balancing Boots of the Grim Jest",   source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Ring 1',    item: 'Occlusion of Void',                  source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Ring 2',    item: 'Omission of Light',                  source: 'Corewarden Nysarra',    location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Light Company Guidon',               source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Main Hand', item: "Belo'ren's Swift Talon",             source: 'Void Ember',            location: "March on Quel'Danas" },
      { slot: 'Off Hand',  item: "Farstrider's Mercy",                 source: 'Crafted',               location: 'Blacksmithing' },
    ]},
  },

  shaman: {
    elemental:   { items: [
      { slot: 'Head',      item: 'Locus of the Primal Core',           source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',         source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: 'Tempests of the Primal Core',        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Guardian of the Primal Core',        source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Chest',     item: 'Embrace of the Primal Core',         source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Fallen King's Cuffs",                source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Hands',     item: 'Earthgrips of the Primal Core',      source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "World Tender's Barkclasp",           source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Legs',      item: 'Greaves of the Divine Guile',        source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Feet',      item: "World Tender's Rootslippers",        source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Ring 1',    item: 'Platinum Star Band',                 source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Ring 2',    item: "Sin'dorei Band of Hope",             source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: 'Emberwing Feather',                  source: 'Emberdawn',             location: 'Windrunner Spire (M+)' },
      { slot: 'Main Hand', item: 'Excavating Cudgel',                  source: 'Kalis',                 location: 'Windrunner Spire (M+)' },
      { slot: 'Off Hand',  item: 'Ward of the Spellbreaker',           source: 'Seranel Sunlash',       location: "Magister's Terrace (M+)" },
    ]},
    enhancement: { items: [
      { slot: 'Head',      item: 'Locus of the Primal Core',           source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Amulet of the Abyssal Hymn',         source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Shoulders', item: 'Tempests of the Primal Core',        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",           source: 'Crafted',               location: 'Leatherworking' },
      { slot: 'Chest',     item: 'Embrace of the Primal Core',         source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Fallen King's Cuffs",                source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Hands',     item: 'Earthgrips of the Primal Core',      source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Ceinture of the Primal Core',        source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Legs',      item: 'Eternal Flame Scaleguards',          source: 'Dungeon Drop',          location: "Algeth'ar Academy (M+)" },
      { slot: 'Feet',      item: 'Whipcoil Sabatons',                  source: 'Dungeon Drop',          location: 'Windrunner Spire (M+)' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                    source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Omission of Light',                  source: 'Corewarden Nysarra',    location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Algeth'ar Puzzle Box",               source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Main Hand', item: "Clutchmate's Caress",                source: 'Vaelgor & Ezzorak',     location: 'The Voidspire' },
      { slot: 'Off Hand',  item: "Farstrider's Chopper",               source: 'Crafted',               location: 'Blacksmithing' },
    ]},
    restoration: { items: [
      { slot: 'Head',      item: 'Oblivion Guise',                     source: 'Midnight Falls',        location: "March on Quel'Danas" },
      { slot: 'Neck',      item: 'Ribbon of Coiled Malice',            source: 'Fallen-King Salhadaar', location: 'The Voidspire' },
      { slot: 'Shoulders', item: 'Tempests of the Primal Core',        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Back',      item: 'Guardian of the Primal Core',        source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Chest',     item: 'Embrace of the Primal Core',         source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: 'Cuffs of the Primal Core',           source: 'Tier Catalyst',         location: 'Great Vault / Catalyst' },
      { slot: 'Hands',     item: 'Earthgrips of the Primal Core',      source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Waistcord of the Judged',            source: 'Lightblinded Vanguard', location: "March on Quel'Danas" },
      { slot: 'Legs',      item: 'Leggings of the Primal Core',        source: 'Tier Set',              location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Sabatons of Obscurement',            source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Ring 1',    item: "Sin'dorei Band of Hope",             source: "Belo'ren",              location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Platinum Star Band',                 source: 'Echo of Doragosa',      location: "Algeth'ar Academy (M+)" },
      { slot: 'Trinket 1', item: 'Gaze of the Alnseer',                source: 'Chimaerus',             location: 'The Dreamrift' },
      { slot: 'Trinket 2', item: "Locus-Walker's Ribbon",              source: 'Crown of the Cosmos',   location: 'The Voidspire' },
      { slot: 'Main Hand', item: 'Weight of Command',                  source: 'Imperator Averzian',    location: 'The Voidspire' },
      { slot: 'Shield',    item: 'Reflux Reflector',                   source: 'Dungeon Drop',          location: 'Nexus-Point Xenas (M+)' },
    ]},
  },

  warlock: {
    affliction:  { items: [
      { slot: 'Head',      item: "Abyssal Immolator's Smoldering Flames", source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',                source: 'Crown of the Cosmos', location: 'The Voidspire' },
      { slot: 'Shoulders', item: 'Echoing Void Mantle',                   source: 'Dungeon Drop',        location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",              source: 'Crafted',             location: 'Leatherworking' },
      { slot: 'Chest',     item: "Abyssal Immolator's Dreadrobe",         source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Martyr's Bindings",                     source: 'Crafted',             location: 'Tailoring' },
      { slot: 'Hands',     item: "Abyssal Immolator's Grasps",            source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: 'Clasp of Compliance',                   source: 'Dungeon Drop',        location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Legs',      item: "Abyssal Immolator's Pillars",           source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Slippers of the Midnight Flame',        source: 'Dungeon Drop',        location: 'Seat of the Triumvirate (M+)' },
      { slot: 'Ring 1',    item: 'Eye of Midnight',                       source: 'Midnight Falls',      location: "March on Quel'Danas" },
      { slot: 'Ring 2',    item: 'Occlusion of Void',                     source: 'Dungeon Drop',        location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Emberwing Feather',                     source: 'Emberdawn',           location: 'Windrunner Spire (M+)' },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',                   source: 'Chimaerus',           location: 'The Dreamrift' },
      { slot: 'Main Hand', item: 'Splitshroud Stinger',                   source: 'Gemellus',            location: "Magister's Terrace (M+)" },
      { slot: 'Off Hand',  item: 'Grimoire of the Eternal Light',         source: 'Vorasius',            location: 'The Voidspire' },
    ]},
    demonology:  { items: [
      { slot: 'Head',      item: "Abyssal Immolator's Smoldering Flames", source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',                source: 'Crown of the Cosmos', location: 'The Voidspire' },
      { slot: 'Shoulders', item: 'Mantle of Dark Devotion',               source: 'Dungeon Drop',        location: 'Windrunner Spire (M+)' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",              source: 'Crafted',             location: 'Leatherworking' },
      { slot: 'Chest',     item: "Abyssal Immolator's Dreadrobe",         source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Martyr's Bindings",                     source: 'Crafted',             location: 'Tailoring' },
      { slot: 'Hands',     item: "Abyssal Immolator's Grasps",            source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Abyssal Immolator's Blazing Core",      source: 'Tier Catalyst',       location: 'Great Vault / Catalyst' },
      { slot: 'Legs',      item: "Abyssal Immolator's Pillars",           source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Dream-Scorched Striders',               source: 'Chimaerus',           location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Omission of Light',                     source: 'Corewarden Nysarra',  location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Ring 2',    item: 'Occlusion of Void',                     source: 'Dungeon Drop',        location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Emberwing Feather',                     source: 'Emberdawn',           location: 'Windrunner Spire (M+)' },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',                   source: 'Chimaerus',           location: 'The Dreamrift' },
      { slot: 'Main Hand', item: 'Umbral Spire of Zuraal',                source: 'Zuraal the Ascended', location: 'Seat of the Triumvirate (M+)' },
    ]},
    destruction: { items: [
      { slot: 'Head',      item: "Abyssal Immolator's Smoldering Flames", source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Neck',      item: 'Eternal Voidsong Chain',                source: 'Crown of the Cosmos', location: 'The Voidspire' },
      { slot: 'Shoulders', item: 'Mantle of Dark Devotion',               source: 'Dungeon Drop',        location: 'Windrunner Spire (M+)' },
      { slot: 'Back',      item: "Adherent's Silken Shroud",              source: 'Crafted',             location: 'Leatherworking' },
      { slot: 'Chest',     item: "Abyssal Immolator's Dreadrobe",         source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Wrists',    item: "Martyr's Bindings",                     source: 'Crafted',             location: 'Tailoring' },
      { slot: 'Hands',     item: "Abyssal Immolator's Grasps",            source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Waist',     item: "Abyssal Immolator's Blazing Core",      source: 'Tier Catalyst',       location: 'Great Vault / Catalyst' },
      { slot: 'Legs',      item: "Abyssal Immolator's Pillars",           source: 'Tier Set',            location: 'Raid / Great Vault / Catalyst' },
      { slot: 'Feet',      item: 'Dream-Scorched Striders',               source: 'Chimaerus',           location: 'The Dreamrift' },
      { slot: 'Ring 1',    item: 'Omission of Light',                     source: 'Corewarden Nysarra',  location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Ring 2',    item: 'Occlusion of Void',                     source: 'Dungeon Drop',        location: 'Nexus-Point Xenas (M+)' },
      { slot: 'Trinket 1', item: 'Emberwing Feather',                     source: 'Emberdawn',           location: 'Windrunner Spire (M+)' },
      { slot: 'Trinket 2', item: 'Gaze of the Alnseer',                   source: 'Chimaerus',           location: 'The Dreamrift' },
      { slot: 'Main Hand', item: 'Umbral Spire of Zuraal',                source: 'Zuraal the Ascended', location: 'Seat of the Triumvirate (M+)' },
    ]},
  },

};
