/* ═══════════════════════════════════════════════════════════
   WORLD EVENT DATA  —  Patch 12.0.5 · May 2026 – May 2027
   Single source of truth for both the inline event display
   (index.html) and the full Event Calendar (events.html).

   Format: { name, url, start: YYYY-MM-DD, end: YYYY-MM-DD,
             desc, tags[] }

   Dates are parsed as UTC midnight for consistent comparison.
   The index page uses only name/url/start/end.
   events.html uses name/url/start/end/desc/tags.
═══════════════════════════════════════════════════════════ */
const EVENTS = [
  { name: 'Pet Battle Bonus Event',       url: 'https://www.wowhead.com/event=565/pet-battle-bonus-event',
    start: '2026-05-19', end: '2026-05-26',
    desc: 'Bonus pet battle experience and a weekly quest rewarding a Sack of Pet Supplies. Good week to level battle pets.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Delves Bonus Event',            url: 'https://www.wowhead.com/event=1559/delves-bonus-event',
    start: '2026-05-19', end: '2026-05-26',
    desc: 'Bonus rewards from Delves this week. Weekly quest rewards extra loot. Combine with your normal Delve progression.',
    tags: ['tag-optional','tag-delve','tag-world'] },
  { name: 'PvP Brawl: Deepwind Dunk',     url: 'https://www.wowhead.com/event=1240/pvp-brawl-deepwind-dunk',
    start: '2026-05-19', end: '2026-05-26',
    desc: 'Wacky basketball-style PvP brawl in Deepwind Gorge. Fun distraction with a weekly quest reward.',
    tags: ['tag-optional','tag-pvp'] },
  { name: 'Midnight Dungeon Event',        url: 'https://www.wowhead.com/event=1802/midnight-dungeon-event',
    start: '2026-05-26', end: '2026-06-02',
    desc: 'Bonus rewards from Midnight dungeons. Weekly quest from the Adventure Guide rewards a piece of gear.',
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: 'PvP Brawl: Shado-Pan Showdown',url: 'https://www.wowhead.com/event=1233/pvp-brawl-shado-pan-showdown',
    start: '2026-05-26', end: '2026-06-02',
    desc: '1v1 PvP brawl in a Shado-Pan arena. Weekly quest reward.',
    tags: ['tag-optional','tag-pvp'] },
  { name: "Glowcap Festival",              url: 'https://www.wowhead.com/event=648/glowcap-festival',
    start: '2026-05-27', end: '2026-05-28',
    desc: 'Short micro-holiday in Zangarmarsh celebrating the Sporeggar. Collect Glowcaps and earn reputation.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Timewalking Dungeon Event',     url: 'https://www.wowhead.com/event=1263/timewalking-dungeon-event',
    start: '2026-06-02', end: '2026-06-09',
    desc: 'Weekly quest rewards a cache of loot. Timewalking dungeons scale you down to old content. Good for Timewalking badges and mounts.',
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: 'Darkmoon Faire',               url: 'https://www.wowhead.com/event=479/darkmoon-faire',
    start: '2026-06-06', end: '2026-06-13',
    desc: 'Monthly carnival on Darkmoon Island. Profession skill-up quests (+5 skill each), Darkmoon Prize Tickets for mounts/toys/heirlooms, and the Darkmoon Races.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Thousand Boat Bash',           url: 'https://www.wowhead.com/event=642/thousand-boat-bash',
    start: '2026-06-06', end: '2026-06-09',
    desc: 'Micro-holiday on the seas of Azeroth. Ride boats and celebrate.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Arena Skirmish Bonus Event',   url: 'https://www.wowhead.com/event=561/arena-skirmish-bonus-event',
    start: '2026-06-09', end: '2026-06-16',
    desc: 'Bonus Honor from unrated Arena Skirmishes. Weekly quest rewards a piece of PvP gear.',
    tags: ['tag-optional','tag-pvp'] },
  { name: 'PvP Brawl: Cooking Impossible',url: 'https://www.wowhead.com/event=1047/pvp-brawl-cooking-impossible',
    start: '2026-06-09', end: '2026-06-16',
    desc: 'Cooking-themed PvP brawl. Weekly quest reward.',
    tags: ['tag-optional','tag-pvp'] },
  { name: 'World Quest Bonus Event',      url: 'https://www.wowhead.com/event=592/world-quest-bonus-event',
    start: '2026-06-16', end: '2026-06-23',
    desc: 'Bonus reputation and rewards from World Quests. Weekly quest rewards a cache. Good week to grind Renown.',
    tags: ['tag-optional','tag-world'] },
  { name: 'PvP Brawl: Temple of Hotmogu', url: 'https://www.wowhead.com/event=1170/pvp-brawl-temple-of-hotmogu',
    start: '2026-06-16', end: '2026-06-23',
    desc: 'Hold the orb, score points, try not to get destroyed. Weekly PvP brawl quest reward.',
    tags: ['tag-optional','tag-pvp'] },
  { name: 'Timewalking Dungeon Event',    url: 'https://www.wowhead.com/event=1669/timewalking-dungeon-event',
    start: '2026-06-23', end: '2026-06-30',
    desc: 'Second June Timewalking window. Weekly quest cache reward.',
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: 'Midsummer Fire Festival',      url: 'https://www.wowhead.com/event=341/midsummer-fire-festival',
    start: '2026-06-21', end: '2026-07-05',
    desc: 'Honor the flames across Azeroth for Burning Blossoms. Spend them on cosmetics, pets, and the Frostscythe transmog. Ahune boss drops the Icebound Frostbrood Vanquisher mount.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Darkspear Dash',               url: 'https://www.wowhead.com/event=1793/darkspear-dash',
    start: '2026-06-27', end: '2026-06-29',
    desc: 'Racing micro-holiday on the Echo Isles. Troll-themed obstacle course.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Battleground Bonus Event',     url: 'https://www.wowhead.com/event=563/battleground-bonus-event',
    start: '2026-06-30', end: '2026-07-07',
    desc: 'Bonus Honor from random Battlegrounds. Weekly quest rewards Conquest.',
    tags: ['tag-optional','tag-pvp'] },
  { name: 'PvP Brawl: Packed House',      url: 'https://www.wowhead.com/event=667/pvp-brawl-packed-house',
    start: '2026-07-07', end: '2026-07-14',
    desc: 'Battleground brawl with a packed roster. Weekly quest reward.',
    tags: ['tag-optional','tag-pvp'] },
  { name: 'Fireworks Spectacular',        url: 'https://www.wowhead.com/event=62/fireworks-spectacular',
    start: '2026-07-04', end: '2026-07-05',
    desc: 'Independence Day micro-holiday. Fireworks displays in major cities.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Timewalking Dungeon Event',    url: 'https://www.wowhead.com/event=1703/timewalking-dungeon-event',
    start: '2026-07-14', end: '2026-07-21',
    desc: 'Timewalking window. Weekly quest cache reward.',
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: 'Timewalking Dungeon Event',    url: 'https://www.wowhead.com/event=1704/timewalking-dungeon-event',
    start: '2026-07-14', end: '2026-07-22',
    desc: 'Second concurrent Timewalking window. Weekly quest cache reward.',
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: 'PvP Brawl: Deep Six',          url: 'https://www.wowhead.com/event=702/pvp-brawl-deep-six',
    start: '2026-07-14', end: '2026-07-21',
    desc: 'Six-player free-for-all PvP brawl. Weekly quest reward.',
    tags: ['tag-optional','tag-pvp'] },
  { name: 'Luminous Luminaries',          url: 'https://www.wowhead.com/event=1054/luminous-luminaries',
    start: '2026-07-13', end: '2026-07-14',
    desc: 'Micro-holiday. Collect glowing lanterns across Azeroth.',
    tags: ['tag-optional','tag-world'] },
  { name: 'PvP Brawl: Arathi Blizzard',   url: 'https://www.wowhead.com/event=666/pvp-brawl-arathi-blizzard',
    start: '2026-07-21', end: '2026-07-28',
    desc: 'Arathi Basin in a blizzard — reduced visibility, chaotic fun. Weekly quest reward.',
    tags: ['tag-optional','tag-pvp'] },
  { name: 'Auction House Dance Party',    url: 'https://www.wowhead.com/event=692/auction-house-dance-party',
    start: '2026-07-22', end: '2026-07-23',
    desc: 'The Auction House becomes a dance floor. Micro-holiday with no rewards but maximum vibes.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Trial of Style',               url: 'https://www.wowhead.com/event=691/trial-of-style',
    start: '2026-08-01', end: '2026-08-08',
    desc: 'Transmog competition event. Build a themed outfit and get judged by other players. Rewards Trial of Style Tokens for cosmetic gear.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Timewalking Dungeon Event',    url: 'https://www.wowhead.com/event=1508/timewalking-dungeon-event',
    start: '2026-08-04', end: '2026-08-11',
    desc: 'Timewalking window. Weekly quest cache reward.',
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: 'Free T-Shirt Day',             url: 'https://www.wowhead.com/event=1053/free-t-shirt-day',
    start: '2026-08-16', end: '2026-08-17',
    desc: 'Blizzard anniversary micro-holiday. Grab a free in-game t-shirt toy.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Northrend Cup',                url: 'https://www.wowhead.com/event=1429/northrend-cup',
    start: '2026-08-25', end: '2026-09-08',
    desc: 'Dragonriding race circuit across Northrend. Earn Riders of Azeroth Badges for cosmetic rewards.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Outland Timewalking',          url: 'https://www.wowhead.com/event=559/outland-timewalking-dungeon-event',
    start: '2026-08-25', end: '2026-09-01',
    desc: 'Timewalking through Burning Crusade dungeons. Weekly quest cache. Good for TBC-era mounts.',
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: 'Northrend Timewalking',        url: 'https://www.wowhead.com/event=562/northrend-timewalking-dungeon-event',
    start: '2026-09-15', end: '2026-09-22',
    desc: "Timewalking through Wrath of the Lich King dungeons. Badge vendor sells Reins of the Ironbound Proto-Drake.",
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: "Pirates' Day",                 url: 'https://www.wowhead.com/event=398/pirates-day',
    start: '2026-09-19', end: '2026-09-20',
    desc: 'One-day micro-holiday in Booty Bay. Dress as a pirate, drink grog.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Brewfest',                     url: 'https://www.wowhead.com/event=372/brewfest',
    start: '2026-09-20', end: '2026-10-06',
    desc: 'Ram racing, Coren Direbrew boss (drops mounts and trinkets), and Brewfest Tokens for cosmetic rewards and heirlooms.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Harvest Festival',             url: 'https://www.wowhead.com/event=321/harvest-festival',
    start: '2026-09-21', end: '2026-09-28',
    desc: "Quiet lore holiday honoring fallen heroes. Visit Uther's tomb or Grom Hellscream's monument for a buff.",
    tags: ['tag-optional','tag-world'] },
  { name: 'Cataclysm Timewalking',        url: 'https://www.wowhead.com/event=587/cataclysm-timewalking-dungeon-event',
    start: '2026-10-06', end: '2026-10-13',
    desc: 'Timewalking through Cataclysm dungeons. Badge vendor and weekly cache reward.',
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: 'The Great Gnomeregan Run',     url: 'https://www.wowhead.com/event=696/the-great-gnomeregan-run',
    start: '2026-10-10', end: '2026-10-12',
    desc: 'Gnome and Goblin charity race. No combat, just running in costume for fun cosmetic rewards.',
    tags: ['tag-optional','tag-world'] },
  { name: "Hallow's End",                 url: 'https://www.wowhead.com/event=324/hallows-end',
    start: '2026-10-18', end: '2026-11-01',
    desc: 'Halloween event. Headless Horseman boss drops mounts and rings. Trick or Treat for Tricky Treats. Meta-achievement rewards the Hallowed title.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Timewalking Dungeon Event',    url: 'https://www.wowhead.com/event=643/timewalking-dungeon-event',
    start: '2026-10-27', end: '2026-11-03',
    desc: "Timewalking window overlapping Hallow's End. Stack the weekly cache with holiday rewards.",
    tags: ['tag-optional','tag-mythic','tag-world'] },
  { name: 'Day of the Dead',              url: 'https://www.wowhead.com/event=409/day-of-the-dead',
    start: '2026-11-01', end: '2026-11-03',
    desc: 'Short holiday at graveyards. Dance with the dead for the Macabre Marionette pet and holiday food buff.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Moonkin Festival',             url: 'https://www.wowhead.com/event=694/moonkin-festival',
    start: '2026-11-12', end: '2026-11-13',
    desc: 'Micro-holiday celebrating boomkins. Dance with owlkin across Azeroth.',
    tags: ['tag-optional','tag-world'] },
  { name: "WoW's 22nd Anniversary",       url: 'https://www.wowhead.com/event=1808/wows-22nd-anniversary',
    start: '2026-11-17', end: '2026-12-08',
    desc: 'Annual anniversary event. Rewards anniversary-themed pets, a toy, and anniversary tokens.',
    tags: ['tag-optional','tag-world'] },
  { name: "Pilgrim's Bounty",             url: 'https://www.wowhead.com/event=404/pilgrims-bounty',
    start: '2026-11-22', end: '2026-11-29',
    desc: 'Thanksgiving-themed event. Cooking skill-up quests, the Plump Turkey pet, and the Pilgrim title meta-achievement.',
    tags: ['tag-optional','tag-world'] },
  { name: "Wanderer's Festival",          url: 'https://www.wowhead.com/event=1052/wanderers-festival',
    start: '2026-12-07', end: '2026-12-08',
    desc: "Micro-holiday in Pandaria. Join the Wanderer's Festival on the Timeless Isle for pets and buffs.",
    tags: ['tag-optional','tag-world'] },
  { name: 'Feast of Winter Veil',         url: 'https://www.wowhead.com/event=141/feast-of-winter-veil',
    start: '2026-12-15', end: '2027-01-02',
    desc: "Christmas event. Father Winter gifts under the tree on Dec 25th. Metzen the Reindeer rescue quest, Stolen Treats dailies, and cosmetic rewards including Winter Veil hats.",
    tags: ['tag-optional','tag-world'] },
  { name: 'Fireworks Celebration',        url: 'https://www.wowhead.com/event=658/fireworks-celebration',
    start: '2026-12-31', end: '2027-01-01',
    desc: "New Year's Eve micro-holiday. Fireworks in Booty Bay and major cities at midnight.",
    tags: ['tag-optional','tag-world'] },
  { name: 'Call of the Scarab',           url: 'https://www.wowhead.com/event=638/call-of-the-scarab',
    start: '2027-01-21', end: '2027-01-24',
    desc: 'Faction-based micro-holiday commemorating the opening of AQ. Contribute resources for faction bragging rights.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Lunar Festival',               url: 'https://www.wowhead.com/event=327/lunar-festival',
    start: '2027-02-02', end: '2027-02-16',
    desc: 'Chinese New Year-inspired event. Visit Elders across Azeroth for Coins of Ancestry → buy cosmetics, the Lunar Festival Fireworks, and the Elder title.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Love is in the Air',           url: 'https://www.wowhead.com/event=423/love-is-in-the-air',
    start: '2027-02-08', end: '2027-02-22',
    desc: "Valentine's event. Apothecary Hummel boss drops the Toxic Wasteling pet and Big Love Rocket mount. Daily charm quests for Love Tokens.",
    tags: ['tag-optional','tag-world'] },
  { name: 'Hatching of the Hippogryphs',  url: 'https://www.wowhead.com/event=634/hatching-of-the-hippogryphs',
    start: '2027-02-23', end: '2027-02-24',
    desc: 'Micro-holiday in Feralas. Watch hippogryph eggs hatch and earn a temporary baby hippogryph companion.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Kalimdor Cup',                 url: 'https://www.wowhead.com/event=1395/kalimdor-cup',
    start: '2027-02-23', end: '2027-03-09',
    desc: 'Dragonriding race circuit across Kalimdor. Riders of Azeroth Badges for cosmetic rewards.',
    tags: ['tag-optional','tag-world'] },
  { name: "Un'Goro Madness",              url: 'https://www.wowhead.com/event=644/ungoro-madness',
    start: '2027-03-17', end: '2027-03-20',
    desc: "Micro-holiday in Un'Goro Crater. Dinosaurs rampage, chaos ensues.",
    tags: ['tag-optional','tag-world'] },
  { name: 'Noblegarden',                  url: 'https://www.wowhead.com/event=181/noblegarden',
    start: '2027-03-29', end: '2027-04-05',
    desc: 'Easter event. Hunt Noblegarden Eggs for Chocolates → buy the Swift Springstrider mount, dresses, and the Mystical Spring Bouquet.',
    tags: ['tag-optional','tag-world'] },
  { name: 'March of the Tadpoles',        url: 'https://www.wowhead.com/event=647/march-of-the-tadpoles',
    start: '2027-04-05', end: '2027-04-06',
    desc: 'Micro-holiday in Pandaria. Escort Jinyu tadpoles to safety.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Volunteer Guard Day',          url: 'https://www.wowhead.com/event=635/volunteer-guard-day',
    start: '2027-04-28', end: '2027-04-29',
    desc: 'Micro-holiday. Stand around as an honorary city guard.',
    tags: ['tag-optional','tag-world'] },
  { name: 'Eastern Kingdoms Cup',         url: 'https://www.wowhead.com/event=1400/eastern-kingdoms-cup',
    start: '2027-08-24', end: '2027-09-07',
    desc: 'Dragonriding race circuit across Eastern Kingdoms. Riders of Azeroth Badges for cosmetic rewards.',
    tags: ['tag-optional','tag-world'] },
];

